#!/usr/bin/env bash
# install and configure haproxy

sudo apt-get update
sudo apt-get install -y haproxy
sudo chown -R $USER:$USER /etc/haproxy

echo "  frontend http-in
                bind *:80
                mode http
                default_backend servers

        backend servers
                mode http
                balance roundrobin
                server 145060-web-01 52.201.219.224:80 check
                server 145060-web-02 54.237.72.39:80 check
        " >> /etc/haproxy/haproxy.cfg
        sudo service haproxy restart
