#!/usr/bin/env bash
# make nginx listen on port 80

sudo apt-get install -y curl
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
