#!usr/bin/env bash
#configure nginx server to listen on port 80 then kill process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
