#!/usr/bin/env bash
#this script prints a string 10 times but aslo adds an if statement

i=0
while((i<10))
do
	if [[ $i -eq 3 ]]
	then
		echo "Bad luck"
	elif [[ $i -eq 7 ]]
	then
		echo "Good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
