#!/usr/bin/env bash
# install ufw and setup rules to block incoming traffic
# except for ports 22, 443, and 80

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo 8ufw allow 80
